/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Event = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'reminder' : IDL.Bool,
  'date' : IDL.Text,
  'createdAt' : Time,
  'time' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
  'updateEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Event = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'reminder' : IDL.Bool,
    'date' : IDL.Text,
    'createdAt' : Time,
    'time' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
    'updateEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };